
ROM_LEN ?= 0x100000
RAM_LEN ?= 0x40000

# 
LINKER_SCRIPT ?= nrf9151_nonsecure.ld

FLASHFILE ?= $(BINFILE)

PROGRAMMER ?= jlink
JLINK_DEVICE = NRF9151_XXCA

include $(RIOTCPU)/nrf5x_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
